apiVersion: v1
kind: Service
metadata:
  name: employees-app-svc
  labels:
    app: employees
spec:
  selector:
    app:  employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
