apiVersion: v1
kind: Service
metadata:
  name: employees-app-svc-v2
  labels:
    app: employees
    version: v2
spec:
  selector:
    app: employees
    version: v2  # Selecting the pods with version 2 label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Exposing on NodePort 30001 for version 2 of employees webapp
  type: NodePort
