apiVersion: v1
kind: Service
metadata:
  name: webapp-flask-app-svc
  labels:
    app: webapp-flask-app
spec:
  selector:
    app: webapp-flask-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
