apiVersion: v1
kind: Pod
metadata:
  name: employees-app-pod
  namespace: webapp
spec:
  containers:
    - name: employees
      image: 063129952770.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.1-app
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql-svc.sqldb.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
