apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: mysql  # Adding label to the ReplicaSet itself
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 063129952770.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.1-db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
